platform :ios, '15.0'
use_frameworks!

target 'SyRtcSDKExample' do
  # 使用本地Pod（需要先构建rtc-ios-sdk）
  pod 'SyRtcSDK', :path => '../'
  
  # 或使用远程Pod
  # pod 'SyRtcSDK', '~> 1.2.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
